Upgraded react-advanced-page-properties sample to SPFx 1.16.1.
- Run yarn install
Renamed package-lock.json to remove and save as backup. Using yarn.lock now.

Used recommendations from cli for microsoft365.

Version check
`> m365 spfx doctor --spfxVersion 1.15.0 --output text
`

Upgrade guidance:
`> m365 spfx project upgrade --output tour
`
or
`> m365 spfx project upgrade --shell powershell --output text
`
Also upgrade the packages to 1.16.0:
https://learn.microsoft.com/en-us/sharepoint/dev/spfx/release-1.16

To fix the gulp error `Type '(version: "3") => Promise<MSGraphClientV3>' is not assignable to type '() => Promise<any>'`
https://github.com/pnp/sp-dev-fx-controls-react/issues/851

Edit and save changes to these files: AdvancedPageProperties.tsx, AdvancedPagePropertiesWebPart.ts.
Typecast props.context to `any` in the call to sp.setup.

src/webparts/advancedPageProperties/AdvancedPagePropertiesWebPart.ts
`gulp serve` error.
`error TS2416: Property 'dataVersion' in type 'AdvancedPagePropertiesWebPart' is not assignable to the same property in base type 'BaseClientSideWebPart<IAdvancedPagePropertiesWebPartProps>'.`
Workaround:
https://sharepoint.stackexchange.com/questions/284689/getting-property-overridden-error-for-dataversion-in-spfx
https://dreamsof.dev/2020-09-21-typescript-upgrade-breaking-dataversion-get-override-spfx11/
"
Either fix it by using an older version of TypeScript

Within Visual Studio Code; press [F1] -> type “TypeScript” -> select “TypeScript: Select TypeScript version…”

or add ts-ignore on top of the code:
"
`
// @ts-ignore
protected get dataVersion(): Version {
  return Version.parse('1.0');
}
`

- Still getting the following error when running gulp serve:
`
Error - 'lint' sub task errored after 2.07 ms
 TSLint is not supported for rush-stack-compiler-4.X packages.
`
I tried the advice from here to update the gulpfile.js (maybe I did not implement the advice correctly):
https://techcommunity.microsoft.com/t5/sharepoint-developer/tslint-is-not-supported-for-rush-stack-compiler-4-x-packages/m-p/3267711