Upgraded react-directory sample up to SPFx 1.17.2.
- Use Node v16.19.0 (use nvm Node Version Manager)
- Switched to yarn because npm could not handle some of the dependency ordering.
(remove or rename package-lock.json to package-lock.json.bak. Then run yarn install)
- Upgraded to latest SharePoint Framework version based on recommendations from running *m365 spfx project upgrade --shell powershell --output text*
https://pnp.github.io/cli-microsoft365/
- Make sure to use UTF8 file encoding for .eslintrc.js file.
- Fixed error about debounce by assigning debounced function to a new constant variable.
"How to throttle AND debounce an autocomplete input in React"( https://www.peterbe.com/plog/how-to-throttle-and-debounce-an-autocomplete-input-in-react )
The error message was: "src/webparts/directory/components/DirectoryHook.tsx(13,26): error TS7016: Could not find a declaration file for module 'throttle-debounce'."
Followed instructions for upgrading to newer SharePoint Framework (SPFx) by running SharePoint Framework Doctor in CLI for Microsoft 365 to get the recommendations.
- Disabled linter warnings for many lines.
- Kept office-ui-fabric-react at the same version what was already in the package.json. Upgrading to a newer version caused errors for gulp bundle.
- Add types for @types/throttle-debounce
yarn add @types/throttle-debounce
- Add types for @types/react-js-pagination
yarn add @types/react-js-pagination
- Add @microsoft/sp-application-base.
yarn add --dev --exact @microsoft/sp-application-base
- Changed the method signature of _searchBoxChanged() event handler to match the signature of the event.